// flow-typed signature: e130092698c928ca0e9545fc6cb87c67
// flow-typed version: <<STUB>>/babel-plugin-transform-react-jsx-self_v^6.22.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-react-jsx-self'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-react-jsx-self' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-react-jsx-self/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-react-jsx-self/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-jsx-self/lib/index'>;
}
