// flow-typed signature: af7c494ebe4b3170b41a1b315d235a5b
// flow-typed version: <<STUB>>/babel-plugin-inline-import_v^2.0.4/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-inline-import'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-inline-import' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-inline-import/build/helper' {
  declare module.exports: any;
}

declare module 'babel-plugin-inline-import/build/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-inline-import/build/helper.js' {
  declare module.exports: $Exports<'babel-plugin-inline-import/build/helper'>;
}
declare module 'babel-plugin-inline-import/build/index.js' {
  declare module.exports: $Exports<'babel-plugin-inline-import/build/index'>;
}
