// flow-typed signature: 3e558def0644025ba4b9b7c5987b3686
// flow-typed version: <<STUB>>/phenomic_v^0.21.0/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'phenomic'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'phenomic' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'phenomic/lib/_utils/array-unique/index' {
  declare module.exports: any;
}

declare module 'phenomic/lib/_utils/beautify-html/index' {
  declare module.exports: any;
}

declare module 'phenomic/lib/_utils/bins' {
  declare module.exports: any;
}

declare module 'phenomic/lib/_utils/cache/webpack' {
  declare module.exports: any;
}

declare module 'phenomic/lib/_utils/catch-links/index' {
  declare module.exports: any;
}

declare module 'phenomic/lib/_utils/error-formatter/index' {
  declare module.exports: any;
}

declare module 'phenomic/lib/_utils/jsdom/index' {
  declare module.exports: any;
}

declare module 'phenomic/lib/_utils/log/index' {
  declare module.exports: any;
}

declare module 'phenomic/lib/_utils/normalize-base-url/index' {
  declare module.exports: any;
}

declare module 'phenomic/lib/_utils/offline/runtime' {
  declare module.exports: any;
}

declare module 'phenomic/lib/_utils/offline/webpack' {
  declare module.exports: any;
}

declare module 'phenomic/lib/_utils/path-to-uri/index' {
  declare module.exports: any;
}

declare module 'phenomic/lib/_utils/serialize/index' {
  declare module.exports: any;
}

declare module 'phenomic/lib/_utils/urlify/index' {
  declare module.exports: any;
}

declare module 'phenomic/lib/bin/check-engine' {
  declare module.exports: any;
}

declare module 'phenomic/lib/bin/commands/setup/index' {
  declare module.exports: any;
}

declare module 'phenomic/lib/bin/commands/setup/questions' {
  declare module.exports: any;
}

declare module 'phenomic/lib/bin/index' {
  declare module.exports: any;
}

declare module 'phenomic/lib/bin/phenomic' {
  declare module.exports: any;
}

declare module 'phenomic/lib/builder/dynamic-require' {
  declare module.exports: any;
}

declare module 'phenomic/lib/builder/index' {
  declare module.exports: any;
}

declare module 'phenomic/lib/builder/post-build' {
  declare module.exports: any;
}

declare module 'phenomic/lib/builder/server' {
  declare module.exports: any;
}

declare module 'phenomic/lib/builder/webpack/config.browser' {
  declare module.exports: any;
}

declare module 'phenomic/lib/builder/webpack/config.common' {
  declare module.exports: any;
}

declare module 'phenomic/lib/builder/webpack/config.node' {
  declare module.exports: any;
}

declare module 'phenomic/lib/builder/webpack/index' {
  declare module.exports: any;
}

declare module 'phenomic/lib/builder/webpack/log-formatter' {
  declare module.exports: any;
}

declare module 'phenomic/lib/builder/webpack/sortAssets' {
  declare module.exports: any;
}

declare module 'phenomic/lib/client/hot-md' {
  declare module.exports: any;
}

declare module 'phenomic/lib/client/index' {
  declare module.exports: any;
}

declare module 'phenomic/lib/client/should-update-scroll' {
  declare module.exports: any;
}

declare module 'phenomic/lib/components/BodyContainer/index' {
  declare module.exports: any;
}

declare module 'phenomic/lib/components/ContextProvider/index' {
  declare module.exports: any;
}

declare module 'phenomic/lib/components/Html/index' {
  declare module.exports: any;
}

declare module 'phenomic/lib/components/Link/index' {
  declare module.exports: any;
}

declare module 'phenomic/lib/components/PageContainer/component' {
  declare module.exports: any;
}

declare module 'phenomic/lib/components/PageContainer/index' {
  declare module.exports: any;
}

declare module 'phenomic/lib/configurator/definitions' {
  declare module.exports: any;
}

declare module 'phenomic/lib/configurator/index' {
  declare module.exports: any;
}

declare module 'phenomic/lib/configurator/minimal-validator' {
  declare module.exports: any;
}

declare module 'phenomic/lib/configurator/validators' {
  declare module.exports: any;
}

declare module 'phenomic/lib/configurator/validators/assets' {
  declare module.exports: any;
}

declare module 'phenomic/lib/configurator/validators/baseUrl' {
  declare module.exports: any;
}

declare module 'phenomic/lib/configurator/validators/devPort' {
  declare module.exports: any;
}

declare module 'phenomic/lib/configurator/validators/offline' {
  declare module.exports: any;
}

declare module 'phenomic/lib/configurator/validators/production' {
  declare module.exports: any;
}

declare module 'phenomic/lib/configurator/yargs' {
  declare module.exports: any;
}

declare module 'phenomic/lib/enhance-collection/index' {
  declare module.exports: any;
}

declare module 'phenomic/lib/eslint-config-recommended/index' {
  declare module.exports: any;
}

declare module 'phenomic/lib/index' {
  declare module.exports: any;
}

declare module 'phenomic/lib/Link/index' {
  declare module.exports: any;
}

declare module 'phenomic/lib/loader-feed-webpack-plugin/feed' {
  declare module.exports: any;
}

declare module 'phenomic/lib/loader-feed-webpack-plugin/index' {
  declare module.exports: any;
}

declare module 'phenomic/lib/loader-plugin-init-body-property-from-content/index' {
  declare module.exports: any;
}

declare module 'phenomic/lib/loader-plugin-init-head-property-from-config/index' {
  declare module.exports: any;
}

declare module 'phenomic/lib/loader-plugin-init-head-property-from-content/index' {
  declare module.exports: any;
}

declare module 'phenomic/lib/loader-plugin-init-raw-property-from-content/index' {
  declare module.exports: any;
}

declare module 'phenomic/lib/loader-plugin-init-rawBody-property-from-content/index' {
  declare module.exports: any;
}

declare module 'phenomic/lib/loader-plugin-markdown-init-head.description-property-from-content/index' {
  declare module.exports: any;
}

declare module 'phenomic/lib/loader-plugin-markdown-init-head.description-property-from-content/prune/index' {
  declare module.exports: any;
}

declare module 'phenomic/lib/loader-plugin-markdown-transform-body-property-to-html/index' {
  declare module.exports: any;
}

declare module 'phenomic/lib/loader-preset-default/index' {
  declare module.exports: any;
}

declare module 'phenomic/lib/loader-preset-markdown/index' {
  declare module.exports: any;
}

declare module 'phenomic/lib/loader-sitemap-webpack-plugin/index' {
  declare module.exports: any;
}

declare module 'phenomic/lib/loader/index' {
  declare module.exports: any;
}

declare module 'phenomic/lib/loader/minify' {
  declare module.exports: any;
}

declare module 'phenomic/lib/loader/plugin' {
  declare module.exports: any;
}

declare module 'phenomic/lib/PageContainer/index' {
  declare module.exports: any;
}

declare module 'phenomic/lib/redux/createStore/index' {
  declare module.exports: any;
}

declare module 'phenomic/lib/redux/middlewares/promise' {
  declare module.exports: any;
}

declare module 'phenomic/lib/redux/modules/index' {
  declare module.exports: any;
}

declare module 'phenomic/lib/redux/modules/pages' {
  declare module.exports: any;
}

declare module 'phenomic/lib/static/index' {
  declare module.exports: any;
}

declare module 'phenomic/lib/static/routes-to-urls/index' {
  declare module.exports: any;
}

declare module 'phenomic/lib/static/url-as-html' {
  declare module.exports: any;
}

declare module 'phenomic/lib/stylelint-config-recommended/index' {
  declare module.exports: any;
}

declare module 'phenomic/npm/bin' {
  declare module.exports: any;
}

declare module 'phenomic/npm/postinstall' {
  declare module.exports: any;
}

declare module 'phenomic/src/_utils/array-unique/index' {
  declare module.exports: any;
}

declare module 'phenomic/src/_utils/beautify-html/index' {
  declare module.exports: any;
}

declare module 'phenomic/src/_utils/bins' {
  declare module.exports: any;
}

declare module 'phenomic/src/_utils/cache/webpack' {
  declare module.exports: any;
}

declare module 'phenomic/src/_utils/catch-links/index' {
  declare module.exports: any;
}

declare module 'phenomic/src/_utils/error-formatter/index' {
  declare module.exports: any;
}

declare module 'phenomic/src/_utils/jsdom/index' {
  declare module.exports: any;
}

declare module 'phenomic/src/_utils/log/index' {
  declare module.exports: any;
}

declare module 'phenomic/src/_utils/normalize-base-url/index' {
  declare module.exports: any;
}

declare module 'phenomic/src/_utils/offline/runtime' {
  declare module.exports: any;
}

declare module 'phenomic/src/_utils/offline/webpack' {
  declare module.exports: any;
}

declare module 'phenomic/src/_utils/path-to-uri/index' {
  declare module.exports: any;
}

declare module 'phenomic/src/_utils/serialize/index' {
  declare module.exports: any;
}

declare module 'phenomic/src/_utils/urlify/index' {
  declare module.exports: any;
}

declare module 'phenomic/src/bin/check-engine' {
  declare module.exports: any;
}

declare module 'phenomic/src/bin/commands/setup/index' {
  declare module.exports: any;
}

declare module 'phenomic/src/bin/commands/setup/questions' {
  declare module.exports: any;
}

declare module 'phenomic/src/bin/index' {
  declare module.exports: any;
}

declare module 'phenomic/src/bin/phenomic' {
  declare module.exports: any;
}

declare module 'phenomic/src/builder/dynamic-require' {
  declare module.exports: any;
}

declare module 'phenomic/src/builder/index' {
  declare module.exports: any;
}

declare module 'phenomic/src/builder/post-build' {
  declare module.exports: any;
}

declare module 'phenomic/src/builder/server' {
  declare module.exports: any;
}

declare module 'phenomic/src/builder/webpack/config.browser' {
  declare module.exports: any;
}

declare module 'phenomic/src/builder/webpack/config.common' {
  declare module.exports: any;
}

declare module 'phenomic/src/builder/webpack/config.node' {
  declare module.exports: any;
}

declare module 'phenomic/src/builder/webpack/index' {
  declare module.exports: any;
}

declare module 'phenomic/src/builder/webpack/log-formatter' {
  declare module.exports: any;
}

declare module 'phenomic/src/builder/webpack/sortAssets' {
  declare module.exports: any;
}

declare module 'phenomic/src/client/hot-md' {
  declare module.exports: any;
}

declare module 'phenomic/src/client/index' {
  declare module.exports: any;
}

declare module 'phenomic/src/client/should-update-scroll' {
  declare module.exports: any;
}

declare module 'phenomic/src/components/BodyContainer/index' {
  declare module.exports: any;
}

declare module 'phenomic/src/components/ContextProvider/index' {
  declare module.exports: any;
}

declare module 'phenomic/src/components/Html/index' {
  declare module.exports: any;
}

declare module 'phenomic/src/components/Link/index' {
  declare module.exports: any;
}

declare module 'phenomic/src/components/PageContainer/component' {
  declare module.exports: any;
}

declare module 'phenomic/src/components/PageContainer/index' {
  declare module.exports: any;
}

declare module 'phenomic/src/configurator/definitions' {
  declare module.exports: any;
}

declare module 'phenomic/src/configurator/index' {
  declare module.exports: any;
}

declare module 'phenomic/src/configurator/minimal-validator' {
  declare module.exports: any;
}

declare module 'phenomic/src/configurator/validators' {
  declare module.exports: any;
}

declare module 'phenomic/src/configurator/validators/assets' {
  declare module.exports: any;
}

declare module 'phenomic/src/configurator/validators/baseUrl' {
  declare module.exports: any;
}

declare module 'phenomic/src/configurator/validators/devPort' {
  declare module.exports: any;
}

declare module 'phenomic/src/configurator/validators/offline' {
  declare module.exports: any;
}

declare module 'phenomic/src/configurator/validators/production' {
  declare module.exports: any;
}

declare module 'phenomic/src/configurator/yargs' {
  declare module.exports: any;
}

declare module 'phenomic/src/enhance-collection/index' {
  declare module.exports: any;
}

declare module 'phenomic/src/eslint-config-recommended/index' {
  declare module.exports: any;
}

declare module 'phenomic/src/index' {
  declare module.exports: any;
}

declare module 'phenomic/src/Link/index' {
  declare module.exports: any;
}

declare module 'phenomic/src/loader-feed-webpack-plugin/feed' {
  declare module.exports: any;
}

declare module 'phenomic/src/loader-feed-webpack-plugin/index' {
  declare module.exports: any;
}

declare module 'phenomic/src/loader-plugin-init-body-property-from-content/index' {
  declare module.exports: any;
}

declare module 'phenomic/src/loader-plugin-init-head-property-from-config/index' {
  declare module.exports: any;
}

declare module 'phenomic/src/loader-plugin-init-head-property-from-content/index' {
  declare module.exports: any;
}

declare module 'phenomic/src/loader-plugin-init-raw-property-from-content/index' {
  declare module.exports: any;
}

declare module 'phenomic/src/loader-plugin-init-rawBody-property-from-content/index' {
  declare module.exports: any;
}

declare module 'phenomic/src/loader-plugin-markdown-init-head.description-property-from-content/index' {
  declare module.exports: any;
}

declare module 'phenomic/src/loader-plugin-markdown-init-head.description-property-from-content/prune/index' {
  declare module.exports: any;
}

declare module 'phenomic/src/loader-plugin-markdown-transform-body-property-to-html/index' {
  declare module.exports: any;
}

declare module 'phenomic/src/loader-preset-default/index' {
  declare module.exports: any;
}

declare module 'phenomic/src/loader-preset-markdown/index' {
  declare module.exports: any;
}

declare module 'phenomic/src/loader-sitemap-webpack-plugin/index' {
  declare module.exports: any;
}

declare module 'phenomic/src/loader/index' {
  declare module.exports: any;
}

declare module 'phenomic/src/loader/minify' {
  declare module.exports: any;
}

declare module 'phenomic/src/loader/plugin' {
  declare module.exports: any;
}

declare module 'phenomic/src/PageContainer/index' {
  declare module.exports: any;
}

declare module 'phenomic/src/redux/createStore/index' {
  declare module.exports: any;
}

declare module 'phenomic/src/redux/middlewares/promise' {
  declare module.exports: any;
}

declare module 'phenomic/src/redux/modules/index' {
  declare module.exports: any;
}

declare module 'phenomic/src/redux/modules/pages' {
  declare module.exports: any;
}

declare module 'phenomic/src/static/index' {
  declare module.exports: any;
}

declare module 'phenomic/src/static/routes-to-urls/index' {
  declare module.exports: any;
}

declare module 'phenomic/src/static/url-as-html' {
  declare module.exports: any;
}

declare module 'phenomic/src/stylelint-config-recommended/index' {
  declare module.exports: any;
}

declare module 'phenomic/themes/phenomic-theme-base/postcss.config' {
  declare module.exports: any;
}

declare module 'phenomic/themes/phenomic-theme-base/scripts/phenomic.browser' {
  declare module.exports: any;
}

declare module 'phenomic/themes/phenomic-theme-base/scripts/phenomic.node' {
  declare module.exports: any;
}

declare module 'phenomic/themes/phenomic-theme-base/src/AppContainer' {
  declare module.exports: any;
}

declare module 'phenomic/themes/phenomic-theme-base/src/components/Button/index' {
  declare module.exports: any;
}

declare module 'phenomic/themes/phenomic-theme-base/src/components/Container/index' {
  declare module.exports: any;
}

declare module 'phenomic/themes/phenomic-theme-base/src/components/Content/index' {
  declare module.exports: any;
}

declare module 'phenomic/themes/phenomic-theme-base/src/components/DefaultHeadMeta/index' {
  declare module.exports: any;
}

declare module 'phenomic/themes/phenomic-theme-base/src/components/Footer/index' {
  declare module.exports: any;
}

declare module 'phenomic/themes/phenomic-theme-base/src/components/Header/index' {
  declare module.exports: any;
}

declare module 'phenomic/themes/phenomic-theme-base/src/components/LatestPosts/index' {
  declare module.exports: any;
}

declare module 'phenomic/themes/phenomic-theme-base/src/components/Loading/index' {
  declare module.exports: any;
}

declare module 'phenomic/themes/phenomic-theme-base/src/components/PagePreview/index' {
  declare module.exports: any;
}

declare module 'phenomic/themes/phenomic-theme-base/src/components/PagesList/index' {
  declare module.exports: any;
}

declare module 'phenomic/themes/phenomic-theme-base/src/layouts/Homepage/index' {
  declare module.exports: any;
}

declare module 'phenomic/themes/phenomic-theme-base/src/layouts/Page/index' {
  declare module.exports: any;
}

declare module 'phenomic/themes/phenomic-theme-base/src/layouts/PageError/index' {
  declare module.exports: any;
}

declare module 'phenomic/themes/phenomic-theme-base/src/layouts/Post/index' {
  declare module.exports: any;
}

declare module 'phenomic/themes/phenomic-theme-base/src/metadata' {
  declare module.exports: any;
}

declare module 'phenomic/themes/phenomic-theme-base/src/routes' {
  declare module.exports: any;
}

declare module 'phenomic/themes/phenomic-theme-base/src/store' {
  declare module.exports: any;
}

declare module 'phenomic/themes/phenomic-theme-base/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'phenomic/lib/_utils/array-unique/index.js' {
  declare module.exports: $Exports<'phenomic/lib/_utils/array-unique/index'>;
}
declare module 'phenomic/lib/_utils/beautify-html/index.js' {
  declare module.exports: $Exports<'phenomic/lib/_utils/beautify-html/index'>;
}
declare module 'phenomic/lib/_utils/bins.js' {
  declare module.exports: $Exports<'phenomic/lib/_utils/bins'>;
}
declare module 'phenomic/lib/_utils/cache/webpack.js' {
  declare module.exports: $Exports<'phenomic/lib/_utils/cache/webpack'>;
}
declare module 'phenomic/lib/_utils/catch-links/index.js' {
  declare module.exports: $Exports<'phenomic/lib/_utils/catch-links/index'>;
}
declare module 'phenomic/lib/_utils/error-formatter/index.js' {
  declare module.exports: $Exports<'phenomic/lib/_utils/error-formatter/index'>;
}
declare module 'phenomic/lib/_utils/jsdom/index.js' {
  declare module.exports: $Exports<'phenomic/lib/_utils/jsdom/index'>;
}
declare module 'phenomic/lib/_utils/log/index.js' {
  declare module.exports: $Exports<'phenomic/lib/_utils/log/index'>;
}
declare module 'phenomic/lib/_utils/normalize-base-url/index.js' {
  declare module.exports: $Exports<'phenomic/lib/_utils/normalize-base-url/index'>;
}
declare module 'phenomic/lib/_utils/offline/runtime.js' {
  declare module.exports: $Exports<'phenomic/lib/_utils/offline/runtime'>;
}
declare module 'phenomic/lib/_utils/offline/webpack.js' {
  declare module.exports: $Exports<'phenomic/lib/_utils/offline/webpack'>;
}
declare module 'phenomic/lib/_utils/path-to-uri/index.js' {
  declare module.exports: $Exports<'phenomic/lib/_utils/path-to-uri/index'>;
}
declare module 'phenomic/lib/_utils/serialize/index.js' {
  declare module.exports: $Exports<'phenomic/lib/_utils/serialize/index'>;
}
declare module 'phenomic/lib/_utils/urlify/index.js' {
  declare module.exports: $Exports<'phenomic/lib/_utils/urlify/index'>;
}
declare module 'phenomic/lib/bin/check-engine.js' {
  declare module.exports: $Exports<'phenomic/lib/bin/check-engine'>;
}
declare module 'phenomic/lib/bin/commands/setup/index.js' {
  declare module.exports: $Exports<'phenomic/lib/bin/commands/setup/index'>;
}
declare module 'phenomic/lib/bin/commands/setup/questions.js' {
  declare module.exports: $Exports<'phenomic/lib/bin/commands/setup/questions'>;
}
declare module 'phenomic/lib/bin/index.js' {
  declare module.exports: $Exports<'phenomic/lib/bin/index'>;
}
declare module 'phenomic/lib/bin/phenomic.js' {
  declare module.exports: $Exports<'phenomic/lib/bin/phenomic'>;
}
declare module 'phenomic/lib/builder/dynamic-require.js' {
  declare module.exports: $Exports<'phenomic/lib/builder/dynamic-require'>;
}
declare module 'phenomic/lib/builder/index.js' {
  declare module.exports: $Exports<'phenomic/lib/builder/index'>;
}
declare module 'phenomic/lib/builder/post-build.js' {
  declare module.exports: $Exports<'phenomic/lib/builder/post-build'>;
}
declare module 'phenomic/lib/builder/server.js' {
  declare module.exports: $Exports<'phenomic/lib/builder/server'>;
}
declare module 'phenomic/lib/builder/webpack/config.browser.js' {
  declare module.exports: $Exports<'phenomic/lib/builder/webpack/config.browser'>;
}
declare module 'phenomic/lib/builder/webpack/config.common.js' {
  declare module.exports: $Exports<'phenomic/lib/builder/webpack/config.common'>;
}
declare module 'phenomic/lib/builder/webpack/config.node.js' {
  declare module.exports: $Exports<'phenomic/lib/builder/webpack/config.node'>;
}
declare module 'phenomic/lib/builder/webpack/index.js' {
  declare module.exports: $Exports<'phenomic/lib/builder/webpack/index'>;
}
declare module 'phenomic/lib/builder/webpack/log-formatter.js' {
  declare module.exports: $Exports<'phenomic/lib/builder/webpack/log-formatter'>;
}
declare module 'phenomic/lib/builder/webpack/sortAssets.js' {
  declare module.exports: $Exports<'phenomic/lib/builder/webpack/sortAssets'>;
}
declare module 'phenomic/lib/client/hot-md.js' {
  declare module.exports: $Exports<'phenomic/lib/client/hot-md'>;
}
declare module 'phenomic/lib/client/index.js' {
  declare module.exports: $Exports<'phenomic/lib/client/index'>;
}
declare module 'phenomic/lib/client/should-update-scroll.js' {
  declare module.exports: $Exports<'phenomic/lib/client/should-update-scroll'>;
}
declare module 'phenomic/lib/components/BodyContainer/index.js' {
  declare module.exports: $Exports<'phenomic/lib/components/BodyContainer/index'>;
}
declare module 'phenomic/lib/components/ContextProvider/index.js' {
  declare module.exports: $Exports<'phenomic/lib/components/ContextProvider/index'>;
}
declare module 'phenomic/lib/components/Html/index.js' {
  declare module.exports: $Exports<'phenomic/lib/components/Html/index'>;
}
declare module 'phenomic/lib/components/Link/index.js' {
  declare module.exports: $Exports<'phenomic/lib/components/Link/index'>;
}
declare module 'phenomic/lib/components/PageContainer/component.js' {
  declare module.exports: $Exports<'phenomic/lib/components/PageContainer/component'>;
}
declare module 'phenomic/lib/components/PageContainer/index.js' {
  declare module.exports: $Exports<'phenomic/lib/components/PageContainer/index'>;
}
declare module 'phenomic/lib/configurator/definitions.js' {
  declare module.exports: $Exports<'phenomic/lib/configurator/definitions'>;
}
declare module 'phenomic/lib/configurator/index.js' {
  declare module.exports: $Exports<'phenomic/lib/configurator/index'>;
}
declare module 'phenomic/lib/configurator/minimal-validator.js' {
  declare module.exports: $Exports<'phenomic/lib/configurator/minimal-validator'>;
}
declare module 'phenomic/lib/configurator/validators.js' {
  declare module.exports: $Exports<'phenomic/lib/configurator/validators'>;
}
declare module 'phenomic/lib/configurator/validators/assets.js' {
  declare module.exports: $Exports<'phenomic/lib/configurator/validators/assets'>;
}
declare module 'phenomic/lib/configurator/validators/baseUrl.js' {
  declare module.exports: $Exports<'phenomic/lib/configurator/validators/baseUrl'>;
}
declare module 'phenomic/lib/configurator/validators/devPort.js' {
  declare module.exports: $Exports<'phenomic/lib/configurator/validators/devPort'>;
}
declare module 'phenomic/lib/configurator/validators/offline.js' {
  declare module.exports: $Exports<'phenomic/lib/configurator/validators/offline'>;
}
declare module 'phenomic/lib/configurator/validators/production.js' {
  declare module.exports: $Exports<'phenomic/lib/configurator/validators/production'>;
}
declare module 'phenomic/lib/configurator/yargs.js' {
  declare module.exports: $Exports<'phenomic/lib/configurator/yargs'>;
}
declare module 'phenomic/lib/enhance-collection/index.js' {
  declare module.exports: $Exports<'phenomic/lib/enhance-collection/index'>;
}
declare module 'phenomic/lib/eslint-config-recommended/index.js' {
  declare module.exports: $Exports<'phenomic/lib/eslint-config-recommended/index'>;
}
declare module 'phenomic/lib/index.js' {
  declare module.exports: $Exports<'phenomic/lib/index'>;
}
declare module 'phenomic/lib/Link/index.js' {
  declare module.exports: $Exports<'phenomic/lib/Link/index'>;
}
declare module 'phenomic/lib/loader-feed-webpack-plugin/feed.js' {
  declare module.exports: $Exports<'phenomic/lib/loader-feed-webpack-plugin/feed'>;
}
declare module 'phenomic/lib/loader-feed-webpack-plugin/index.js' {
  declare module.exports: $Exports<'phenomic/lib/loader-feed-webpack-plugin/index'>;
}
declare module 'phenomic/lib/loader-plugin-init-body-property-from-content/index.js' {
  declare module.exports: $Exports<'phenomic/lib/loader-plugin-init-body-property-from-content/index'>;
}
declare module 'phenomic/lib/loader-plugin-init-head-property-from-config/index.js' {
  declare module.exports: $Exports<'phenomic/lib/loader-plugin-init-head-property-from-config/index'>;
}
declare module 'phenomic/lib/loader-plugin-init-head-property-from-content/index.js' {
  declare module.exports: $Exports<'phenomic/lib/loader-plugin-init-head-property-from-content/index'>;
}
declare module 'phenomic/lib/loader-plugin-init-raw-property-from-content/index.js' {
  declare module.exports: $Exports<'phenomic/lib/loader-plugin-init-raw-property-from-content/index'>;
}
declare module 'phenomic/lib/loader-plugin-init-rawBody-property-from-content/index.js' {
  declare module.exports: $Exports<'phenomic/lib/loader-plugin-init-rawBody-property-from-content/index'>;
}
declare module 'phenomic/lib/loader-plugin-markdown-init-head.description-property-from-content/index.js' {
  declare module.exports: $Exports<'phenomic/lib/loader-plugin-markdown-init-head.description-property-from-content/index'>;
}
declare module 'phenomic/lib/loader-plugin-markdown-init-head.description-property-from-content/prune/index.js' {
  declare module.exports: $Exports<'phenomic/lib/loader-plugin-markdown-init-head.description-property-from-content/prune/index'>;
}
declare module 'phenomic/lib/loader-plugin-markdown-transform-body-property-to-html/index.js' {
  declare module.exports: $Exports<'phenomic/lib/loader-plugin-markdown-transform-body-property-to-html/index'>;
}
declare module 'phenomic/lib/loader-preset-default/index.js' {
  declare module.exports: $Exports<'phenomic/lib/loader-preset-default/index'>;
}
declare module 'phenomic/lib/loader-preset-markdown/index.js' {
  declare module.exports: $Exports<'phenomic/lib/loader-preset-markdown/index'>;
}
declare module 'phenomic/lib/loader-sitemap-webpack-plugin/index.js' {
  declare module.exports: $Exports<'phenomic/lib/loader-sitemap-webpack-plugin/index'>;
}
declare module 'phenomic/lib/loader/index.js' {
  declare module.exports: $Exports<'phenomic/lib/loader/index'>;
}
declare module 'phenomic/lib/loader/minify.js' {
  declare module.exports: $Exports<'phenomic/lib/loader/minify'>;
}
declare module 'phenomic/lib/loader/plugin.js' {
  declare module.exports: $Exports<'phenomic/lib/loader/plugin'>;
}
declare module 'phenomic/lib/PageContainer/index.js' {
  declare module.exports: $Exports<'phenomic/lib/PageContainer/index'>;
}
declare module 'phenomic/lib/redux/createStore/index.js' {
  declare module.exports: $Exports<'phenomic/lib/redux/createStore/index'>;
}
declare module 'phenomic/lib/redux/middlewares/promise.js' {
  declare module.exports: $Exports<'phenomic/lib/redux/middlewares/promise'>;
}
declare module 'phenomic/lib/redux/modules/index.js' {
  declare module.exports: $Exports<'phenomic/lib/redux/modules/index'>;
}
declare module 'phenomic/lib/redux/modules/pages.js' {
  declare module.exports: $Exports<'phenomic/lib/redux/modules/pages'>;
}
declare module 'phenomic/lib/static/index.js' {
  declare module.exports: $Exports<'phenomic/lib/static/index'>;
}
declare module 'phenomic/lib/static/routes-to-urls/index.js' {
  declare module.exports: $Exports<'phenomic/lib/static/routes-to-urls/index'>;
}
declare module 'phenomic/lib/static/url-as-html.js' {
  declare module.exports: $Exports<'phenomic/lib/static/url-as-html'>;
}
declare module 'phenomic/lib/stylelint-config-recommended/index.js' {
  declare module.exports: $Exports<'phenomic/lib/stylelint-config-recommended/index'>;
}
declare module 'phenomic/npm/bin.js' {
  declare module.exports: $Exports<'phenomic/npm/bin'>;
}
declare module 'phenomic/npm/postinstall.js' {
  declare module.exports: $Exports<'phenomic/npm/postinstall'>;
}
declare module 'phenomic/src/_utils/array-unique/index.js' {
  declare module.exports: $Exports<'phenomic/src/_utils/array-unique/index'>;
}
declare module 'phenomic/src/_utils/beautify-html/index.js' {
  declare module.exports: $Exports<'phenomic/src/_utils/beautify-html/index'>;
}
declare module 'phenomic/src/_utils/bins.js' {
  declare module.exports: $Exports<'phenomic/src/_utils/bins'>;
}
declare module 'phenomic/src/_utils/cache/webpack.js' {
  declare module.exports: $Exports<'phenomic/src/_utils/cache/webpack'>;
}
declare module 'phenomic/src/_utils/catch-links/index.js' {
  declare module.exports: $Exports<'phenomic/src/_utils/catch-links/index'>;
}
declare module 'phenomic/src/_utils/error-formatter/index.js' {
  declare module.exports: $Exports<'phenomic/src/_utils/error-formatter/index'>;
}
declare module 'phenomic/src/_utils/jsdom/index.js' {
  declare module.exports: $Exports<'phenomic/src/_utils/jsdom/index'>;
}
declare module 'phenomic/src/_utils/log/index.js' {
  declare module.exports: $Exports<'phenomic/src/_utils/log/index'>;
}
declare module 'phenomic/src/_utils/normalize-base-url/index.js' {
  declare module.exports: $Exports<'phenomic/src/_utils/normalize-base-url/index'>;
}
declare module 'phenomic/src/_utils/offline/runtime.js' {
  declare module.exports: $Exports<'phenomic/src/_utils/offline/runtime'>;
}
declare module 'phenomic/src/_utils/offline/webpack.js' {
  declare module.exports: $Exports<'phenomic/src/_utils/offline/webpack'>;
}
declare module 'phenomic/src/_utils/path-to-uri/index.js' {
  declare module.exports: $Exports<'phenomic/src/_utils/path-to-uri/index'>;
}
declare module 'phenomic/src/_utils/serialize/index.js' {
  declare module.exports: $Exports<'phenomic/src/_utils/serialize/index'>;
}
declare module 'phenomic/src/_utils/urlify/index.js' {
  declare module.exports: $Exports<'phenomic/src/_utils/urlify/index'>;
}
declare module 'phenomic/src/bin/check-engine.js' {
  declare module.exports: $Exports<'phenomic/src/bin/check-engine'>;
}
declare module 'phenomic/src/bin/commands/setup/index.js' {
  declare module.exports: $Exports<'phenomic/src/bin/commands/setup/index'>;
}
declare module 'phenomic/src/bin/commands/setup/questions.js' {
  declare module.exports: $Exports<'phenomic/src/bin/commands/setup/questions'>;
}
declare module 'phenomic/src/bin/index.js' {
  declare module.exports: $Exports<'phenomic/src/bin/index'>;
}
declare module 'phenomic/src/bin/phenomic.js' {
  declare module.exports: $Exports<'phenomic/src/bin/phenomic'>;
}
declare module 'phenomic/src/builder/dynamic-require.js' {
  declare module.exports: $Exports<'phenomic/src/builder/dynamic-require'>;
}
declare module 'phenomic/src/builder/index.js' {
  declare module.exports: $Exports<'phenomic/src/builder/index'>;
}
declare module 'phenomic/src/builder/post-build.js' {
  declare module.exports: $Exports<'phenomic/src/builder/post-build'>;
}
declare module 'phenomic/src/builder/server.js' {
  declare module.exports: $Exports<'phenomic/src/builder/server'>;
}
declare module 'phenomic/src/builder/webpack/config.browser.js' {
  declare module.exports: $Exports<'phenomic/src/builder/webpack/config.browser'>;
}
declare module 'phenomic/src/builder/webpack/config.common.js' {
  declare module.exports: $Exports<'phenomic/src/builder/webpack/config.common'>;
}
declare module 'phenomic/src/builder/webpack/config.node.js' {
  declare module.exports: $Exports<'phenomic/src/builder/webpack/config.node'>;
}
declare module 'phenomic/src/builder/webpack/index.js' {
  declare module.exports: $Exports<'phenomic/src/builder/webpack/index'>;
}
declare module 'phenomic/src/builder/webpack/log-formatter.js' {
  declare module.exports: $Exports<'phenomic/src/builder/webpack/log-formatter'>;
}
declare module 'phenomic/src/builder/webpack/sortAssets.js' {
  declare module.exports: $Exports<'phenomic/src/builder/webpack/sortAssets'>;
}
declare module 'phenomic/src/client/hot-md.js' {
  declare module.exports: $Exports<'phenomic/src/client/hot-md'>;
}
declare module 'phenomic/src/client/index.js' {
  declare module.exports: $Exports<'phenomic/src/client/index'>;
}
declare module 'phenomic/src/client/should-update-scroll.js' {
  declare module.exports: $Exports<'phenomic/src/client/should-update-scroll'>;
}
declare module 'phenomic/src/components/BodyContainer/index.js' {
  declare module.exports: $Exports<'phenomic/src/components/BodyContainer/index'>;
}
declare module 'phenomic/src/components/ContextProvider/index.js' {
  declare module.exports: $Exports<'phenomic/src/components/ContextProvider/index'>;
}
declare module 'phenomic/src/components/Html/index.js' {
  declare module.exports: $Exports<'phenomic/src/components/Html/index'>;
}
declare module 'phenomic/src/components/Link/index.js' {
  declare module.exports: $Exports<'phenomic/src/components/Link/index'>;
}
declare module 'phenomic/src/components/PageContainer/component.js' {
  declare module.exports: $Exports<'phenomic/src/components/PageContainer/component'>;
}
declare module 'phenomic/src/components/PageContainer/index.js' {
  declare module.exports: $Exports<'phenomic/src/components/PageContainer/index'>;
}
declare module 'phenomic/src/configurator/definitions.js' {
  declare module.exports: $Exports<'phenomic/src/configurator/definitions'>;
}
declare module 'phenomic/src/configurator/index.js' {
  declare module.exports: $Exports<'phenomic/src/configurator/index'>;
}
declare module 'phenomic/src/configurator/minimal-validator.js' {
  declare module.exports: $Exports<'phenomic/src/configurator/minimal-validator'>;
}
declare module 'phenomic/src/configurator/validators.js' {
  declare module.exports: $Exports<'phenomic/src/configurator/validators'>;
}
declare module 'phenomic/src/configurator/validators/assets.js' {
  declare module.exports: $Exports<'phenomic/src/configurator/validators/assets'>;
}
declare module 'phenomic/src/configurator/validators/baseUrl.js' {
  declare module.exports: $Exports<'phenomic/src/configurator/validators/baseUrl'>;
}
declare module 'phenomic/src/configurator/validators/devPort.js' {
  declare module.exports: $Exports<'phenomic/src/configurator/validators/devPort'>;
}
declare module 'phenomic/src/configurator/validators/offline.js' {
  declare module.exports: $Exports<'phenomic/src/configurator/validators/offline'>;
}
declare module 'phenomic/src/configurator/validators/production.js' {
  declare module.exports: $Exports<'phenomic/src/configurator/validators/production'>;
}
declare module 'phenomic/src/configurator/yargs.js' {
  declare module.exports: $Exports<'phenomic/src/configurator/yargs'>;
}
declare module 'phenomic/src/enhance-collection/index.js' {
  declare module.exports: $Exports<'phenomic/src/enhance-collection/index'>;
}
declare module 'phenomic/src/eslint-config-recommended/index.js' {
  declare module.exports: $Exports<'phenomic/src/eslint-config-recommended/index'>;
}
declare module 'phenomic/src/index.js' {
  declare module.exports: $Exports<'phenomic/src/index'>;
}
declare module 'phenomic/src/Link/index.js' {
  declare module.exports: $Exports<'phenomic/src/Link/index'>;
}
declare module 'phenomic/src/loader-feed-webpack-plugin/feed.js' {
  declare module.exports: $Exports<'phenomic/src/loader-feed-webpack-plugin/feed'>;
}
declare module 'phenomic/src/loader-feed-webpack-plugin/index.js' {
  declare module.exports: $Exports<'phenomic/src/loader-feed-webpack-plugin/index'>;
}
declare module 'phenomic/src/loader-plugin-init-body-property-from-content/index.js' {
  declare module.exports: $Exports<'phenomic/src/loader-plugin-init-body-property-from-content/index'>;
}
declare module 'phenomic/src/loader-plugin-init-head-property-from-config/index.js' {
  declare module.exports: $Exports<'phenomic/src/loader-plugin-init-head-property-from-config/index'>;
}
declare module 'phenomic/src/loader-plugin-init-head-property-from-content/index.js' {
  declare module.exports: $Exports<'phenomic/src/loader-plugin-init-head-property-from-content/index'>;
}
declare module 'phenomic/src/loader-plugin-init-raw-property-from-content/index.js' {
  declare module.exports: $Exports<'phenomic/src/loader-plugin-init-raw-property-from-content/index'>;
}
declare module 'phenomic/src/loader-plugin-init-rawBody-property-from-content/index.js' {
  declare module.exports: $Exports<'phenomic/src/loader-plugin-init-rawBody-property-from-content/index'>;
}
declare module 'phenomic/src/loader-plugin-markdown-init-head.description-property-from-content/index.js' {
  declare module.exports: $Exports<'phenomic/src/loader-plugin-markdown-init-head.description-property-from-content/index'>;
}
declare module 'phenomic/src/loader-plugin-markdown-init-head.description-property-from-content/prune/index.js' {
  declare module.exports: $Exports<'phenomic/src/loader-plugin-markdown-init-head.description-property-from-content/prune/index'>;
}
declare module 'phenomic/src/loader-plugin-markdown-transform-body-property-to-html/index.js' {
  declare module.exports: $Exports<'phenomic/src/loader-plugin-markdown-transform-body-property-to-html/index'>;
}
declare module 'phenomic/src/loader-preset-default/index.js' {
  declare module.exports: $Exports<'phenomic/src/loader-preset-default/index'>;
}
declare module 'phenomic/src/loader-preset-markdown/index.js' {
  declare module.exports: $Exports<'phenomic/src/loader-preset-markdown/index'>;
}
declare module 'phenomic/src/loader-sitemap-webpack-plugin/index.js' {
  declare module.exports: $Exports<'phenomic/src/loader-sitemap-webpack-plugin/index'>;
}
declare module 'phenomic/src/loader/index.js' {
  declare module.exports: $Exports<'phenomic/src/loader/index'>;
}
declare module 'phenomic/src/loader/minify.js' {
  declare module.exports: $Exports<'phenomic/src/loader/minify'>;
}
declare module 'phenomic/src/loader/plugin.js' {
  declare module.exports: $Exports<'phenomic/src/loader/plugin'>;
}
declare module 'phenomic/src/PageContainer/index.js' {
  declare module.exports: $Exports<'phenomic/src/PageContainer/index'>;
}
declare module 'phenomic/src/redux/createStore/index.js' {
  declare module.exports: $Exports<'phenomic/src/redux/createStore/index'>;
}
declare module 'phenomic/src/redux/middlewares/promise.js' {
  declare module.exports: $Exports<'phenomic/src/redux/middlewares/promise'>;
}
declare module 'phenomic/src/redux/modules/index.js' {
  declare module.exports: $Exports<'phenomic/src/redux/modules/index'>;
}
declare module 'phenomic/src/redux/modules/pages.js' {
  declare module.exports: $Exports<'phenomic/src/redux/modules/pages'>;
}
declare module 'phenomic/src/static/index.js' {
  declare module.exports: $Exports<'phenomic/src/static/index'>;
}
declare module 'phenomic/src/static/routes-to-urls/index.js' {
  declare module.exports: $Exports<'phenomic/src/static/routes-to-urls/index'>;
}
declare module 'phenomic/src/static/url-as-html.js' {
  declare module.exports: $Exports<'phenomic/src/static/url-as-html'>;
}
declare module 'phenomic/src/stylelint-config-recommended/index.js' {
  declare module.exports: $Exports<'phenomic/src/stylelint-config-recommended/index'>;
}
declare module 'phenomic/themes/phenomic-theme-base/postcss.config.js' {
  declare module.exports: $Exports<'phenomic/themes/phenomic-theme-base/postcss.config'>;
}
declare module 'phenomic/themes/phenomic-theme-base/scripts/phenomic.browser.js' {
  declare module.exports: $Exports<'phenomic/themes/phenomic-theme-base/scripts/phenomic.browser'>;
}
declare module 'phenomic/themes/phenomic-theme-base/scripts/phenomic.node.js' {
  declare module.exports: $Exports<'phenomic/themes/phenomic-theme-base/scripts/phenomic.node'>;
}
declare module 'phenomic/themes/phenomic-theme-base/src/AppContainer.js' {
  declare module.exports: $Exports<'phenomic/themes/phenomic-theme-base/src/AppContainer'>;
}
declare module 'phenomic/themes/phenomic-theme-base/src/components/Button/index.js' {
  declare module.exports: $Exports<'phenomic/themes/phenomic-theme-base/src/components/Button/index'>;
}
declare module 'phenomic/themes/phenomic-theme-base/src/components/Container/index.js' {
  declare module.exports: $Exports<'phenomic/themes/phenomic-theme-base/src/components/Container/index'>;
}
declare module 'phenomic/themes/phenomic-theme-base/src/components/Content/index.js' {
  declare module.exports: $Exports<'phenomic/themes/phenomic-theme-base/src/components/Content/index'>;
}
declare module 'phenomic/themes/phenomic-theme-base/src/components/DefaultHeadMeta/index.js' {
  declare module.exports: $Exports<'phenomic/themes/phenomic-theme-base/src/components/DefaultHeadMeta/index'>;
}
declare module 'phenomic/themes/phenomic-theme-base/src/components/Footer/index.js' {
  declare module.exports: $Exports<'phenomic/themes/phenomic-theme-base/src/components/Footer/index'>;
}
declare module 'phenomic/themes/phenomic-theme-base/src/components/Header/index.js' {
  declare module.exports: $Exports<'phenomic/themes/phenomic-theme-base/src/components/Header/index'>;
}
declare module 'phenomic/themes/phenomic-theme-base/src/components/LatestPosts/index.js' {
  declare module.exports: $Exports<'phenomic/themes/phenomic-theme-base/src/components/LatestPosts/index'>;
}
declare module 'phenomic/themes/phenomic-theme-base/src/components/Loading/index.js' {
  declare module.exports: $Exports<'phenomic/themes/phenomic-theme-base/src/components/Loading/index'>;
}
declare module 'phenomic/themes/phenomic-theme-base/src/components/PagePreview/index.js' {
  declare module.exports: $Exports<'phenomic/themes/phenomic-theme-base/src/components/PagePreview/index'>;
}
declare module 'phenomic/themes/phenomic-theme-base/src/components/PagesList/index.js' {
  declare module.exports: $Exports<'phenomic/themes/phenomic-theme-base/src/components/PagesList/index'>;
}
declare module 'phenomic/themes/phenomic-theme-base/src/layouts/Homepage/index.js' {
  declare module.exports: $Exports<'phenomic/themes/phenomic-theme-base/src/layouts/Homepage/index'>;
}
declare module 'phenomic/themes/phenomic-theme-base/src/layouts/Page/index.js' {
  declare module.exports: $Exports<'phenomic/themes/phenomic-theme-base/src/layouts/Page/index'>;
}
declare module 'phenomic/themes/phenomic-theme-base/src/layouts/PageError/index.js' {
  declare module.exports: $Exports<'phenomic/themes/phenomic-theme-base/src/layouts/PageError/index'>;
}
declare module 'phenomic/themes/phenomic-theme-base/src/layouts/Post/index.js' {
  declare module.exports: $Exports<'phenomic/themes/phenomic-theme-base/src/layouts/Post/index'>;
}
declare module 'phenomic/themes/phenomic-theme-base/src/metadata.js' {
  declare module.exports: $Exports<'phenomic/themes/phenomic-theme-base/src/metadata'>;
}
declare module 'phenomic/themes/phenomic-theme-base/src/routes.js' {
  declare module.exports: $Exports<'phenomic/themes/phenomic-theme-base/src/routes'>;
}
declare module 'phenomic/themes/phenomic-theme-base/src/store.js' {
  declare module.exports: $Exports<'phenomic/themes/phenomic-theme-base/src/store'>;
}
declare module 'phenomic/themes/phenomic-theme-base/webpack.config.js' {
  declare module.exports: $Exports<'phenomic/themes/phenomic-theme-base/webpack.config'>;
}
