// flow-typed signature: 52196d74de5dee1d2ef7eb8ec7ed6b22
// flow-typed version: <<STUB>>/react-modal-video_v^1.0.4/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-modal-video'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-modal-video' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-modal-video/lib/index' {
  declare module.exports: any;
}

declare module 'react-modal-video/src/index' {
  declare module.exports: any;
}

declare module 'react-modal-video/test/dist/index' {
  declare module.exports: any;
}

declare module 'react-modal-video/test/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-modal-video/lib/index.js' {
  declare module.exports: $Exports<'react-modal-video/lib/index'>;
}
declare module 'react-modal-video/src/index.jsx' {
  declare module.exports: $Exports<'react-modal-video/src/index'>;
}
declare module 'react-modal-video/test/dist/index.js' {
  declare module.exports: $Exports<'react-modal-video/test/dist/index'>;
}
declare module 'react-modal-video/test/src/index.jsx' {
  declare module.exports: $Exports<'react-modal-video/test/src/index'>;
}
