// flow-typed signature: c7b6725248b76a917f337d268e491941
// flow-typed version: <<STUB>>/react-svg-inline_v^1.2.0/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-svg-inline'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-svg-inline' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-svg-inline/lib/index' {
  declare module.exports: any;
}

declare module 'react-svg-inline/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-svg-inline/lib/index.js' {
  declare module.exports: $Exports<'react-svg-inline/lib/index'>;
}
declare module 'react-svg-inline/src/index.js' {
  declare module.exports: $Exports<'react-svg-inline/src/index'>;
}
