// flow-typed signature: 01b8223f31c4617433807405594bb9b1
// flow-typed version: <<STUB>>/tachyons_v^4.7.1/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tachyons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'tachyons' {
  declare module.exports: any;
}
