backend:
    name: github
    repo: IntellectionStudio/intellection.kz
    branch: master
public_folder: content
media_folder: content/assets
collections:
    - {name: '404', label: '404 Page', folder: content/404, create: false, fields: [{label: layout, name: layout, widget: string}, {label: route, name: route, widget: string}, {label: body, name: body, widget: text}], meta: [{label: 'Publish Date', name: date, widget: datetime}]}
