backend:
  name: github
  repo: IntellectionStudio/intellection.kz
  branch: master

publish_mode: editorial_workflow
public_folder: "content"
media_folder: "content/assets"

collections:
  - name: "aboutPage"
    label: "AboutPage"
    folder: "content"
    card: {
      type: "alltype",
      text: "title"
    }
    fields:
      - {
          label: "Meta Title",
          name: "title",
          widget: "string"
        }
      - {
          label: "Hero",
          name: "hero",
          widget: "object",
          fields: [
            {
              label: "Title",
              name: "title",
              widget: "string"
            },
            {
              label: "Text",
              name: "text",
              widget: 'text'
            }
          ]
        }
      - {
          label: "Video",
          name: "video",
          widget: "object",
          fields: [
            {
              label: "Title",
              name: "title",
              widget: "string"
            },
            {
              label: "Text",
              name: "text",
              widget: "text"
            },
            {
              label: "Button Text",
              name: "buttonText",
              widget: "string"
            },
            {
              label: "URL",
              name: "url",
              widget: "string"
            }
          ]
        }
    meta:
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime"
        }
